packagecloud: &packagecloud
  provider: packagecloud
  username: cs50
  repository: libcs50
  token: $PACKAGECLOUD_TOKEN
  local-dir: build/deb
  package_glob: *.deb
  skip_cleanup: true
  on:
    branch: master

branches:
  except: "/^v\\d/"
before_install: gem install fpm
install: true
script: make deb
deploy:
  # 12.04
  - <<: *packagecloud
    dist: ubuntu/precise

  # 12.10
  - <<: *packagecloud
    dist: ubuntu/quantal

  # 13.04
  - <<: *packagecloud
    dist: ubuntu/raring

  # 13.10
  - <<: *packagecloud
    dist: ubuntu/saucy

  # 14.04
  - <<: *packagecloud
    dist: ubuntu/trusty

  # 14.10
  - <<: *packagecloud
    dist: ubuntu/utopic

  # 15.04
  - <<: *packagecloud
    dist: ubuntu/vivid

  # 15.10
  - <<: *packagecloud
    dist: ubuntu/wily

  # 16.04
  - <<: *packagecloud
    dist: ubuntu/xenial

  # 16.10
  - <<: *packagecloud
    dist: ubuntu/yakkety

  # 17.04
  - <<: *packagecloud
    dist: ubuntu/zesty

  # 17.10
  - <<: *packagecloud
    dist: ubuntu/artful

  # 18.04
  - <<: *packagecloud
    dist: ubuntu/bionic
notifications:
  slack:
    secure: ISOGlNSGXOrMBrKTnjTWQXVjjoBn78++xF1mUv/PYZxn3J4L4WpybLLjAuBENsD7YeHSaXUnSbIV5mDzlx5Q1cyrS+auGOHqi5xGV01zNBB1Fig1SkUf7zJS8KyjiPKyi+DexnTt1BY4xaA1uGzq9hoGZEPXKHNlz4v1I6f6fHQ=
